Phone Project/Phone Project/Controllers/LeaveTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Phone_Project.Contracts;
using Phone_Project.Data;
using Phone_Project.Models;

namespace Phone_Project.Controllers
{
    public class LeaveTypesController : Controller
    {
        private readonly ILeaveTypeRepository _repo;
        private readonly IMapper _mapper;
        // GET: LeaveTypeController
        public LeaveTypesController(ILeaveTypeRepository repo, IMapper mapper)
        {
            _repo = repo;
            _mapper = mapper;
        }
        public ActionResult Index()
        {
            var leaveTypes = _repo.FindAll().ToList();
            //var model = _mapper.Map<List<LeaveType>, List<LeaveTypeVM>>(leaveTypes);
            //var model = _mapper.Map<List<LeaveType>, List<LeaveTypeVM>>(leaveTypes);
            var model = leaveTypes;
            return View(model);
        }

        // GET: LeaveTypeController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: LeaveTypeController/Create
        public ActionResult Create()
        {
            return View();
           
        }

        // POST: LeaveTypeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(LeaveType model)
        {
            try
            {
                Boolean fag = false;
                if (model.Name != null)
                {
                    if (!ModelState.IsValid)
                    {
                        return View(model);
                    }
                    //var leaveType = _mapper.Map<LeaveTypeVM,LeaveType>(model);
                    //leaveType.DateCreated = new DateTime();
                    var leaveType = model;
                    leaveType.DateCreated = new DateTime();
                    var isSuccess = _repo.Create(leaveType);
                    if (!isSuccess)
                    {
                        ModelState.AddModelError("", "Fail Create LeaveType");
                        return View(model);
                    }
                    fag = true;
                }
                if (fag == true)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return View();
                }

            }
            catch
            {
                return View();
            }
        }

        // GET: LeaveTypeController/Edit/5
        public ActionResult Edit(int id)
        {
            if(!_repo.isExists(id))
            {
                return NotFound();
            }
            LeaveType  leaveType = null;
            leaveType = _repo.FindById(id);
            var model = leaveType;
            return View(model);

        }

        // POST: LeaveTypeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(LeaveType model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(model);
                }
                model.DateCreated = new DateTime();
                var isSuccess = _repo.Update(model);
                if (!isSuccess)
                {
                    ModelState.AddModelError("", "Fail Create LeaveType");
                    return View(model);
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: LeaveTypeController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: LeaveTypeController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Phone Project/Phone Project/Controllers/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Phone_Project.Contracts;
using Phone_Project.Data;

namespace Phone_Project.Controllers
{
    public class QuestionController : Controller
    {
        // GET: QuestionController1
        private readonly IQuestionRepository _repo;
        private readonly IQuestionTypeRepository _repoType;
        private readonly IMapper _mapper;
        // GET: LeaveTypeController
        public QuestionController(IQuestionRepository repo, IMapper mapper, IQuestionTypeRepository repoType)
        {
            _repo = repo;
            _mapper = mapper;
            _repoType = repoType;
        }
        public ActionResult Index()
        {
            var leaveTypes = _repo.FindAll().ToList();
            //var model = _mapper.Map<List<LeaveType>, List<LeaveTypeVM>>(leaveTypes);
            //var model = _mapper.Map<List<LeaveType>, List<LeaveTypeVM>>(leaveTypes);
            foreach(Question item in leaveTypes)
            {
                QuestionType qT = _repoType.FindById(item.IdQType);
                item.QuestionType = qT;
            }
            var model = leaveTypes;
            return View(model);
        }

        /*// GET: QuestionController1/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: QuestionController1/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: QuestionController1/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: QuestionController1/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: QuestionController1/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: QuestionController1/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: QuestionController1/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }*/
    }
}

Phone Project/Phone Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Phone_Project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
    <link href="~/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/vendor/devicons/css/devicons.min.css" rel="stylesheet">
    <link href="~/vendor/simple-line-icons/css/simple-line-icons.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="~/css/resume.min.css" rel="stylesheet">

    <!-- Bootstrap core JavaScript -->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for this template -->
    <script src="~/js/resume.min.js"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Phone_Project</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                  
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Question" asp-action="Index">Question</a>
                        </li>

                        <li class="nav-item">
                            <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Dropdown button
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" asp-controller="LeaveTypes" asp-action="Index">Action</a>
                                    <a class="dropdown-item" href="#">Another action</a>
                                    <a class="dropdown-item" href="#">Something else here</a>
                                </div>
                            </div>

                        </li>
                    </ul>
                </div>

                
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Phone_Project - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>